export enum Color {
  BLACK = 'BLACK',
  WHITE = 'WHITE',
  YELLOW = 'YELLOW',
  GRAY_DARK = 'GRAY_DARK',
  GRAY_MID = 'GRAY_MID',
  GRAY_REGULAR = 'GRAY_REGULAR',
  GRAY_LIGHT = 'GRAY_LIGHT',
  GRAY_LIGHTER = 'GRAY_LIGHTER',
  GRAY_LIGHTEST = 'GRAY_LIGHTEST',
  PRIMARY_REGULAR = 'PRIMARY_REGULAR',
  PRIMARY_HOVER = 'PRIMARY_HOVER',
  PRIMARY_LIGHT = 'PRIMARY_LIGHT',
  PRIMARY_LIGHTEST = 'PRIMARY_LIGHTEST',
  SECONDARY_REGULAR = 'SECONDARY_REGULAR',
  SECONDARY_HOVER = 'SECONDARY_HOVER',
  SECONDARY_LIGHT = 'SECONDARY_LIGHT',
  ALERT_REGULAR = 'ALERT_REGULAR',
  ALERT_LIGHT = 'ALERT_LIGHT',
  INFO = 'INFO',
  TEXT = 'TEXT',
}

export type Palette = Record<Color, string>;
